import pygame
from pygame.locals import *

# Colors
BLACK = (0,0,0)
WHITE = (255,255,255)
DARKGREY = (40,40,40)

# Tile grid
TILESIZE = 16
NUM_TILE_MAZE_X, NUM_TILE_MAZE_Y = 28, 36 + 4

# Basic game constants
FPS = 60
SCREEN_WIDTH, SCREEN_HEIGHT = TILESIZE * NUM_TILE_MAZE_X, TILESIZE * NUM_TILE_MAZE_Y # 16px X 28 tiles, 16px X 36 tiles + 16 X 4 tiles para placar
INITIAL_POSITION_X_GAME, INITIAL_POSITION_Y_GAME = 0, 32
TITLE = "Pac-Dungeon"
BG_COLOR = DARKGREY
GAME_STATE = -1

GRID_WIDTH, GRID_HEIGHT = SCREEN_WIDTH/TILESIZE, SCREEN_HEIGHT/TILESIZE

# KNIGHT
NUM_KNIGHT_HP = 2

# MONSTER